{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Páginas' %}{% endblock %}

{% set active_menu = 'paginas' %}

{% block content %}

<div class="widget simpleTabs">

<ul class="tabs">
    <li><a href="#tab-index">{% trans 'Páginas' %}</a></li>
    <li><a href="#tab-new-article">{% trans 'Nova Página' %}</a></li>
</ul>

<div class="tabs_container">

    <div class="fix"></div>
    <div class="tab_content nopadding" id="tab-index">

    {{ mf.table_search }}
    <table class="tableStatic wide">
        <thead>
            <tr>
                <td>{% trans 'Url' %}</td>
                <td>{% trans 'Titulo da página' %}</td>
                <td>{% trans 'Data' %}</td>
                <td>{% trans 'Status' %}</td>
                <td>&nbsp;</td>
            </tr>
        </thead>

        <tbody>
        {% for pagina in paginas %}
			<tr>
                <td class="highlight"  width="150">
			    	{{pagina.slug}}
			    </td>
			    <td class="highlight"  width="150">
			    	{{pagina.title}}
			    </td>
			    <td>{{pagina.date}}</td>
                <td width="80">{% if pagina.active == '1' %} Desativada {% else %} Ativada {% endif %}</td>

			    <td class="actions">
                <a class="bb-button btn14" href="/central/paginas/{{pagina.slug}}"><img src="images/icons/dark/magnify.png" alt=""></a>
                <a class="bb-button btn14" href="{{ '/paginas/pagina'|alink }}/{{pagina.id}}"><img src="images/icons/dark/pencil.png" alt=""></a>
                {% if pagina.active == '1' %} 
                <a class="bb-button btn14 bb-rm-tr api-link" data-api-redirect="{{ 'paginas'|alink }}" href="{{ 'api/admin/paginas/deactive'|link({'id' : pagina.id}) }}"><img src="images/icons/dark/blocks.png"></a>
                {% else %}
                <a class="bb-button btn14 bb-rm-tr api-link" data-api-redirect="{{ 'paginas'|alink }}" href="{{ 'api/admin/paginas/active'|link({'id' : pagina.id}) }}"><img src="images/icons/dark/unlocked.png" alt=""></a>
                {% endif %}
                <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="{% trans 'Are you sure?' %}" data-api-redirect="{{ 'paginas'|alink }}" href="{{ 'api/admin/paginas/delete'|link({'id' : pagina.id}) }}"><img src="images/icons/dark/trash.png" alt=""></a>
                </td>
			</tr>
        {% else %}
            <tr>
                <td colspan="4">
                    {% trans 'The list is empty' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    {% include "partial_pagination.phtml" with {'list': posts, 'url':'paginas'} %}
    </div>


    <div class="tab_content nopadding" id="tab-new-article">
        <form method="post" action="{{ 'api/admin/paginas/pagina_add'|link }}" class="mainForm api-form" data-api-reload="1">
            <fieldset>
                <div class="rowElem noborder">
                    <label>{% trans 'Titulo' %}:</label>
                    <div class="formRight">
                    <input type="text" name="name" id="titulo" value="">
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem noborder">
                    <label>{% trans 'Url' %}:</label>
                    <div class="formRight">
                    <input type="text" name="slug" id="url" value="">
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Corpo' %}:</label>
                    <div class="formRight">
                        <textarea name="message" cols="5" rows="5" required></textarea>
                    </div>
                    <div class="fix"></div>
                </div>

                <input type="submit" value="{% trans 'Create' %}" class="greyishBtn submitForm" />
            </fieldset>
        </form>
    </div>

</div>

<div class="fix"></div>
</div>
<script>
function string_to_slug(str) {
  str = str.replace(/^\s+|\s+$/g, ''); // trim
  str = str.toLowerCase();
  
  // remove accents, swap ñ for n, etc
  var from = "àáäãâèéëêìíïîòóöôùúüûñç·/_,:;";
  var to   = "aaaaaeeeeiiiioooouuuunc------";
  for (var i=0, l=from.length ; i<l ; i++) {
    str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
  }

  str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
    .replace(/\s+/g, '-') // collapse whitespace and replace by -
    .replace(/-+/g, '-'); // collapse dashes

  return str;
}
$("#titulo").keyup(function(){
        var Text = string_to_slug($(this).val());
        $("#url").val(Text);        
});
$("#url").keyup(function(){
        var Text = string_to_slug($(this).val());
        $(this).val(Text);        
});
</script>
{% endblock %}